"""Automatic startup migration

Revision ID: 3c20a35e43e6
Revises: dffadd547cf6
Create Date: 2026-07-03 13:10:46.603749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c20a35e43e6'
down_revision = 'dffadd547cf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
