"""Automatic startup migration

Revision ID: 83dc7c5c83ef
Revises: a02b1987d645
Create Date: 2026-07-03 06:37:08.731418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83dc7c5c83ef'
down_revision = 'a02b1987d645'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
