"""Automatic startup migration

Revision ID: 8e8dadea4edd
Revises: 83dc7c5c83ef
Create Date: 2026-07-03 11:17:05.579146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e8dadea4edd'
down_revision = '83dc7c5c83ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
