"""Update supplier unique constraint

Revision ID: a02b1987d645
Revises: 78453a88a38e
Create Date: 2026-07-03 04:59:34.647896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a02b1987d645'
down_revision = '78453a88a38e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('suppliers_supplier_name_key'), type_='unique')
        batch_op.create_unique_constraint('uq_business_supplier_name', ['business_id', 'supplier_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_constraint('uq_business_supplier_name', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('suppliers_supplier_name_key'), ['supplier_name'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
