"""Automatic startup migration

Revision ID: dffadd547cf6
Revises: a70f3070460e
Create Date: 2026-07-03 12:53:55.770431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dffadd547cf6'
down_revision = 'a70f3070460e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
